1) put logger back in 2) case insenstive working 3) forgotten unit tests checked in

diff --git a/bin/ctr b/bin/ctr
--- a/bin/ctr
+++ b/bin/ctr
@@ -2,8 +2,14 @@
 
 jvm=$(which java)
 if [ "$jvm" == "" ] ; then
-    $print ERR "java is required, but not found"
-    $print ERR "cannot continue"
+    echo "java is required, but not found"
+    echo "cannot continue"
+    exit 1
+fi
+
+LIB="/usr/local/lib/ctrail.jar"
+if [ ! -e $LIB ] ; then
+    echo "library not found: $LIB"
     exit 1
 fi
 
